### ISSUE TITLE
Cannot add local alba backend

### ISSUE THREAD

**Issue by eduardBM** [openvstorage/framework#587]
Issue introduced by #542 

Error ... albaBackend.totalSize is not a function, in gather_config.js

**Comment by eduardBM** [comment]
openvstorage 2.7.0-rev.3574.6815b75
